---
- name: Install required packages
  ansible.builtin.package:
    name:
      - "{{ item }}"
    state: present
  become: true
  loop: "{{ needed_packages }}"

# tasks file for alert_machinegun
- name: Add the user '{{ alert_machinegun_user }}'
  ansible.builtin.user:
    name: "{{ alert_machinegun_user }}"
    comment: "{{ alert_machinegun_user }}"
    # create_home: false

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ alert_machinegun_user }}"
    group: "{{ alert_machinegun_user }}"
    mode: '0600'
  loop:
    - "{{ alert_machinegun_src_dir }}"
    - "{{ alert_machinegun_data_dir }}"
    - "{{ alert_machinegun_env_dir }}"
    # - "{{ alert_machinegun_config_dir }}/certs"

# - name: Copy programm
#   ansible.builtin.copy:
#     src: alert-machinegun.py
#     dest: "{{ alert_machinegun_src_dir }}/alert-machinegun.py"
#     owner: "{{ alert_machinegun_user }}"
#     group: "{{ alert_machinegun_user }}"
#     mode: '0700'

- name: Copy config
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ alert_machinegun_config_file }}"
    owner: "{{ alert_machinegun_user }}"
    group: "{{ alert_machinegun_user }}"
    mode: '0600'

- name: Encrypt config file
  ansible.builtin.include_tasks: "encrypt_file.yml"
  when: alert_machinegun_encryption_tool

- name: Copy environment file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ alert_machinegun_env_file }}"
    owner: "{{ alert_machinegun_user }}"
    group: "{{ alert_machinegun_user }}"
    mode: '0600'

- name: Copy data files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ alert_machinegun_data_dir }}"
    owner: "{{ alert_machinegun_user }}"
    group: "{{ alert_machinegun_user }}"
    mode: '0600'
  with_fileglob:
    - "data/*.json"

- name: Configure systemd service
  ansible.builtin.template:
    src: alert-machinegun.service.j2
    dest: "/usr/lib/systemd/system/alert-machinegun.service"
    owner: root
    group: root
    mode: '0644'

- name: Configure systemd timer
  ansible.builtin.template:
    src: alert-machinegun.timer.j2
    dest: "/usr/lib/systemd/system/alert-machinegun.timer"
    owner: root
    group: root
    mode: '0644'

- name: Just force systemd to reread configs
  ansible.builtin.command: systemctl daemon-reload
  become: true

- name: Enable systemd service
  ansible.builtin.systemd:
    name: alert-machinegun.service
    enabled: yes

- name: Enable systemd timer
  ansible.builtin.systemd:
    name: alert-machinegun.timer
    state: restarted
    enabled: yes